export const profile = {
  name: "Nitin K. Mishra",
  initials: "NM",
  photo: "/Nitin.png",
  role: "AI Engineer · Multimodal & Agentic Systems",
  location: "Bhopal, India",
  timezone: "Asia/Kolkata",
  available: "Products before Pitch Decks!",
  email: "nitiniszod10@gmail.com",
  github: "https://github.com/nitinog10",
  githubUser: "nitinog10",
  githubLabel: "github.com/nitinog10",
  linkedin: "https://www.linkedin.com/in/nitin-k-mishra-520615331",
  linkedinLabel: "in/nitin-k-mishra",
  // Fill these in to light up the matching pills in the hero. Empty = hidden.
  twitter: "https://x.com/Nitin101_",
  resume: "/NitinResume.pdf",
};

export const bio = [
  { text: "Products and Models shipped end to end.", strong: true },
  { text: "Designing AI systems that can reason, perceive, and act." },
  { text: "Specializing in multimodal AI, LLM fine-tuning, MCP servers, and production-grade agentic architectures." },
];

export const traits = ["Polymath", "Generalist", "AI Native", "Software Craftsman", "Synthesist"];

/* Fill `location` / `type` as you like — blank fields are simply not rendered. */
export const experience = [
  {
    org: "Logorhythms",
    role: "Building",
    years: "March 2026 — Present",
    location: "Bhopal",
    type: "",
    logo: "/experience/logorhythms.png",
    icon: "spark",
    tint: "#a78bfa",
    detail:
      "Building a creative-tech practice where brand systems and web experiences are one discipline, now an AI brand-intelligence platform that takes an idea to a full visual identity.",
  },
  {
    org: "EnTop Learning",
    role: "SDE Intern",
    years: "Jan 2026 — Apr 2026",
    location: "Bangalore",
    type: "Internship",
    logo: "/experience/entoplearning.png",
    icon: "code",
    tint: "#60a5fa",
    detail: "Worked as full stack developer working on the learning management system for the students of US.",
  },
  {
    org: "Student Activity Council, OIST",
    role: "Head Alumni",
    years: "July 2025 — Aug 2026",
    location: "Bhopal",
    type: "",
    logo: "/experience/sacoist.png",
    icon: "cap",
    tint: "#f87171",
    detail: "Manged Alumni relations in college and organized multiple tech nd startup focused events for students of college collaborating with industries.",
  },
  {
    org: "GSSoC'26",
    role: "Mentor",
    years: "April 2025 — Present",
    location: "Remote",
    type: "",
    logo: "/experience/Gssoc26.png",
    icon: "people",
    tint: "#fbbf24",
    detail: "Mentoring contributors on the India's largest open source program on open Source & Agentic AI track.",
  },
  {
    org: "FlyRank AI",
    role: "Frontend AI Engineering Intern",
    years: "May 2026 — July 2026",
    location: "Chicago, Remote",
    type: "Internship",
    logo: "/experience/flyrank ai.png",
    icon: "brain",
    tint: "#38bdf8",
    detail:
      "Worked as a Frontend AI Engineering intern developing intelligent UI workflows, LLM integrations, and interactive user experiences.",
  },
  {
    org: "Haron India",
    role: "AI Developer & Technical Operations",
    years: "Aug 2025 — Dec 2025",
    location: "",
    type: "Internship",
    logo: "/experience/haronindia.png",
    icon: "brain",
    tint: "#5eead4",
    detail: "Worked as an ai developer Buidling ml model for crop disease identification and predicting the cure of the disease.",
  },
  {
    org: "Bugbiceps.in",
    role: "Cofounder",
    years: "",
    location: "",
    type: "",
    logo: "/experience/bugbiceps.png",
    icon: "spark",
    tint: "#38bdf8",
    detail:
      "A production studio which design, build and maintain the systems businesses actually run on: web platforms, mobile apps, AI pipelines and automation that stay fast and stable long after launch.",
  },
];

export const achievements = [
  {
    title: "NASA Space Apps Challenge '25",
    note: "Regional winner · Global nominee",
    rank: "Winner",
    logo: "/achievements/nasa space apps.jpg",
    icon: "trophy",
    tint: "#fbbf24",
  },
  {
    title: "OpenAI Builders Hackathon",
    note: "Selected among the best developers around globe.",
    rank: "Finalist",
    logo: "/achievements/open ai.jpg",
    icon: "medal",
    tint: "#7ee7ef",
  },
  {
    title: "Harvard HPAIR Asia Conference '26",
    note: "Selected as Delegate · Harvard University",
    rank: "Delegate",
    logo: "/achievements/hpair.jpg",
    icon: "award",
    tint: "#ef4444",
  },
  {
    title: "Hackathon wins",
    note: "Across national level and uni level",
    rank: "6×",
    logo: "/achievements/hackathon wins.gif",
    icon: "award",
    tint: "#4ade80",
  },
  {
    title: "Hackathon finalist",
    note: "Shortlisted from open national pools",
    rank: "19×",
    logo: "/achievements/hackathon finalist.jpg",
    icon: "star",
    tint: "#f87171",
  },
];

/* `repo` / `live` are optional — links only render when the URL is present. */
export const projects = [
  {
    name: "Logorhythms",
    img: "/projects/docuverse.png",
    status: "Live",
    featured: true,
    tags: ["Organizational AI", "Knowledge", "Product"],
    stack: ["python", "next", "react", "mcp", "aws", "postgres", "openai"],
    desc: "An AI-powered organizational intelligence platform that connects knowledge from Slack, GitHub, Notion, Jira, and meetings into a single intelligent workspace. It understands your organization's context, answers complex questions, summarizes information, and automates workflows. Instead of just storing data, Logorhythms becomes your company's second brain helping teams make faster, smarter, better-informed decisions.",
    repo: "",
    live: "https://logorhythms.in",
  },
  {
    name: "LedgerFlow",
    img: "/projects/ledgerflow.png",
    status: "Live",
    tags: ["Multi-Agent", "Document AI", "Accounting Automation"],
    stack: ["python", "fastapi", "react", "openai", "postgres"],
    desc: "An accounting automation workflow powered by a 3-agent backend architecture. Replaces raw OCR and manual entry with deterministic validation — validating GSTIN, totals, tax splits, and duplicates, drafting vendor follow-ups for missing fields, and exporting human-verified entries directly to Tally XML or CSV.",
    repo: "",
    live: "",
  },
  {
    name: "ExoVetter",
    img: "/projects/Ecovetter.png",
    status: "Pipeline",
    tags: ["Kepler", "BLS Search", "Ensemble", "Streamlit"],
    stack: ["python", "numpy", "sklearn", "streamlit", "plotly"],
    desc: "Explainable exoplanet transit detection on real Kepler light curves. Transit parameters are derived from flux ,never read from the catalog and then scored by a Vetting Report Card and a calibrated tabular ensemble, with a hard guard that fails the build if a leaky column ever reaches the classifier.",
    repo: "https://github.com/nitinog10/Ecovetter-",
    live: "",
  },
  {
    name: "DiffuMint",
    img: "/projects/diffumint.png",
    status: "Live",
    tags: ["Diffusion", "LoRA", "SD v1.5", "PyTorch"],
    stack: ["python", "pytorch", "huggingface"],
    desc: "Resource conscious LoRA fine-tuning for Stable Diffusion v1.5. By targeting only the UNet attention layers, under 1% of parameters are trained which makes the whole thing viable on 12 GB of VRAM.",
    repo: "https://github.com/nitinog10/DiffuMint-Stable-Diffusion-v1.5-LoRA-Fine-Tuning",
    live: "",
  },
  {
    name: "Air Pulse",
    img: "/projects/airpulse.png",
    status: "Live",
    tags: ["Streamlit", "Geospatial", "ML"],
    stack: ["python", "pandas", "sklearn", "streamlit", "plotly"],
    desc: "Live AQI and pollutant data mapped and filterable across India, paired with month-wise state-level forecasts from a model trained on 24 years of historical readings.",
    repo: "https://github.com/com-the-boys-dev/Air-Pulse-using-streamlit",
    live: "",
  },
  {
    name: "AtmoPredict",
    img: "/projects/Atmopredict.png",
    status: "Award",
    tags: ["NASA Space Apps", "Forecasting", "Time Series"],
    stack: ["python", "pandas", "sklearn", "react"],
    desc: "Winner at the NASA Space Apps Challenge '25, a Future weather prediction model that forecasts up to a year of future dates, trained on NASA POWER API observations from 2006 to 2024.",
    repo: "https://github.com/nitinog10/AtmoPredict",
    live: "",
  },
  {
    name: "SonicPersona",
    img: "/projects/sonicpersona.png",
    status: "Live",
    tags: ["Voice AI", "XTTS-v2", "LoRA", "Whisper"],
    stack: ["python", "pytorch", "huggingface", "gradio"],
    desc: "AI that learns a person's vocal identity. Turns raw audio into a training set, auto-transcribes with Whisper, trains a memory-efficient LoRA adapter on XTTS-v2, and serves real-time inference through Gradio.",
    repo: "https://github.com/nitinog10/SonicPersona",
    live: "",
  },
  {
    name: "CortexDev",
    img: "/projects/cortexdev.png",
    status: "Live",
    tags: ["Code LLM", "LoRA", "CodeGen-350M"],
    stack: ["python", "pytorch", "huggingface"],
    desc: "A lightweight CodeGen-350M fine-tune built to think like a developer,code-only responses with consistent structure and style, no commentary.",
    repo: "https://github.com/nitinog10/CortexDev-Neural-intelligence-for-software-development",
    live: "",
  },
  {
    name: "CampusMitra",
    img: "/projects/campusmitra.png",
    status: "Live",
    tags: ["RAG", "Multilingual", "Agents"],
    stack: ["python", "langchain", "fastapi", "react"],
    desc: "A language-agnostic RAG assistant for universities — admissions, course catalog, and scheduling answered in whichever language the student asks in.",
    repo: "https://github.com/nitinog10/Campus-mitra",
    live: "",
  },
  {
    name: "Hallucination in Indic Multimodal Models",
    img: "/projects/researchpaper.png",
    status: "Paper",
    // a figure, not a UI shot — show the whole plate instead of cropping it
    fit: "contain",
    tags: ["Research", "Multimodal", "Evaluation", "Indic NLP"],
    stack: ["python", "pytorch", "huggingface", "numpy"],
    desc: "The first study of hallucination across Indian languages in text-to-image, speech-to-text, and video models — 14 models (Sarvam, Qwen, Llama, KRUTRIM-2) across 36,047 tasks. Marathi and Odia hallucinate far more than English; native-language prompting cut errors by 12% for Hindi, 9% for Marathi, and 7% for Odia.",
    repo: "",
    live: "",
  },
];

export const education = {
  years: "2024 — 2028",
  degree: "B.Tech — Artificial Intelligence / AIML",
  school: "Oriental Group of Institutes",
  progress: 50,
};

export const quote = "Navigating the space between what is and what could be";
